####  CONFIGURATION SPECIFIC ####
hostname: MOW-RTR-02


default_route: 100.71.60.254

l3_interfaces:
  - interface_type: GigabitEthernet
    interface_id: 1
    description: Internet uplink
    shutdown: false
    ipv4_address: 100.71.60.1/24

  - interface_type: GigabitEthernet
    interface_id: 2
    description: Internal network
    ipv4_address: 172.16.0.253/24
    shutdown: false

  - interface_type: Tunnel
    interface_id: 100
    description: DMVPN
    ipv4_address: 192.168.100.2/24
    source: GigabitEthernet1
    mode: gre multipoint
    shutdown: false

fhrp_priorities:
  - protocol: standby # HSRP
    group: 100
    priority: 100